apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend
spec:
  podSelector: {}  # Applies to all pods in the namespace
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: frontend  # Only allow ingress from pods with this label
  policyTypes:
    - Ingress
