replicaCount: 2

image:
  repository: gcr.io/turnkey-energy-457517-u4/web
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 443
  targetPort: 5000

postgres:
  secretName: web-postgres-secret
  usernameKey: POSTGRES_USER
  passwordKey: POSTGRES_PASSWORD
  db: appdb
  host: postgres-release-postgres.postgres.svc

  pgdata: /var/lib/postgresql/data/pgdata  # PGDATA points to a subfolder
  mountPath: /var/lib/postgresql/data      # Volume mounts to the parent

  persistence:
    enabled: true
    existingClaim: postgres-pvc

ingress:
  enabled: true
  host: aurimas.lt
  managedCertificate: web-cert
