image:
  repository: gcr.io/turnkey-energy-457517-u4/web
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 443
  targetPort: 5000

postgres:
  secretName: web-postgres-secret
  usernameKey: POSTGRES_USER
  passwordKey: POSTGRES_PASSWORD
