namespace: postgres

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: postgres.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

postgres:
  username: ""
  password: ""
  db: "appdb"
  host: "postgres-release-postgres.postgres.svc.cluster.local"
  secretName: "web-postgres-secret"
  pgdata: /var/lib/postgresql/data/pgdata
  mountPath: /var/lib/postgresql/data/pgdata
  persistence:
    enabled: true

storage:
  size: 1Gi
  accessModes:
    - ReadWriteOnce