image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

service:
  port: 5432

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: postgres.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
