name: Deploy Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Apply and Kubernetes Setup'
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write GCP credentials to file
        run: echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/dev
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform/dev
        run: terraform apply -auto-approve

      - name: Extract Terraform Outputs
        id: tf_outputs
        working-directory: terraform/dev
        run: |
          echo "project_id=$(terraform output -raw project_id)" >> $GITHUB_ENV
          echo "cluster_name=$(terraform output -raw cluster_name)" >> $GITHUB_ENV
          echo "region=$(terraform output -raw region)" >> $GITHUB_ENV

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Authenticate gcloud
        run: gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ env.cluster_name }} \
            --region ${{ env.region }} \
            --project ${{ env.project_id }}

      - name: Apply Network Policy
        run: |
          kubectl apply -f k8s/network/network-policy.yaml
